(SIMP-9239) Add GHA workflows to rubygem-simp-rake-helpers
simp/rubygem-simp-rake-helpers pull request #158
Opened 2021-02-05 02:16 UTC by op-ct

This patch adds standardized GitHub Actions to provide GitHub-based
CI/CD workflows.  Among this first batch are:

* PR GLCI - Auto-trigger corresponding GLCI (if actor has write perms)
* Manual: PR GLCI - Team members can trigger corresponding GLCI for a PR
* PR GLCI Cleanup - Clean up any auto-triggered GLCI pipelines/branches

This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.

CI: SKIP MATRIX
[SIMP-9375] #close
[SIMP-9239] #comment Standardized GHA + assets in rubygem-simp-rake-helpers

2021-02-08 14:27 UTC, lnemsick-simp commented on .gitlab-ci.yml
>  # don't set this env var in your gitlab instance
SIMP_FULL_MATRIX isn't used anywhere, so this block can be removed

2021-02-08 14:31 UTC, lnemsick-simp requested changes
Shouldn't this have a GitHub action to run the non-acceptance tests (spec tests, gem build, ...) that appear in the .gitlab-ci.yml?

2021-02-08 23:18 UTC, op-ct commented
> Shouldn't this have a GitHub action to run the non-acceptance tests (spec tests, gem build, ...) that appear in the .gitlab-ci.yml?

I've been adding them here as time allows as an additional courtesy step, but as long as the GLCI trigger works, the tests are covered.  Patches welcome, though!

2021-02-11 16:26 UTC, trevor-vaughan approved these changes

2021-02-11 16:27 UTC, merged